# CI/PR Pipeline that deploys an ARM template to create or update the resources needed by the other pipelines.
trigger:
  branches:
    include:
      - adf_publish


pool:
  vmImage: "ubuntu-latest"

variables:
  - group: devops-iac-vg
  - name: factoryName
  - name: AzureKeyVault_properties_typeProperties_baseUrl
  - name: soucefactory

stages:
- stage: 'CI'
  displayName: 'CI'
  jobs:
  - job: "CI_Job"
    displayName: "CI Job"
    # The CI stage produces two artifacts (notebooks and ADF pipelines).
    # The pipelines Azure Resource Manager templates are stored in a technical branch "adf_publish"
    steps:
      - checkout: git://${{variables['System.TeamProject']}}@adf_publish
      - script: dir $(Build.SourcesDirectory)
      - task: CopyFiles@2
        displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)'
          TargetFolder: '$(Build.artifactstagingdirectory)'
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact drop'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'

- stage: 'CD'
  displayName: 'CD'
  dependsOn: 'CI'
  jobs:
  - deployment: "Deploy_to_ADF"
    environment: prod
    displayName: 'Deploy to ADF'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Bash@3
            displayName: Set variable
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                echo '##vso[task.setvariable variable=factoryName]$(LANDSCAPE_NAME)-adf-$(BASE_NAME)'  
                echo '##vso[task.setvariable variable=soucefactory]dev-adf-$(BASE_NAME)'  
                echo '##vso[task.setvariable variable=AzureKeyVault_properties_typeProperties_baseUrl]https://$(LANDSCAPE_NAME)-akv-$(BASE_NAME).vault.azure.net/'
          - task: Bash@3
            displayName: show variable
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                echo factory name is $(factoryName)
                echo akv uri is  $(AzureKeyVault_properties_typeProperties_baseUrl)
          - task: DownloadBuildArtifacts@0
            displayName: 'download Artifact drop'
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'
          - script: dir $(System.ArtifactsDirectory)/drop
          - task: AzureResourceGroupDeployment@2
            inputs:
              azureSubscription: "$(AZURE_RM_SVC_CONNECTION)"
              action: "Create Or Update Resource Group"
              resourceGroupName: "$(RESOURCE_GROUP)"
              location: $(LOCATION)
              templateLocation: "Linked artifact"
              csmFile: '$(System.ArtifactsDirectory)/drop/$(soucefactory)/ARMTemplateForFactory.json'
              csmParametersFile: '$(System.ArtifactsDirectory)/drop/$(soucefactory)/ARMTemplateParametersForFactory.json'
              overrideParameters: -factoryName $(factoryName) -AzureKeyVault_properties_typeProperties_baseUrl "$(AzureKeyVault_properties_typeProperties_baseUrl)"
              deploymentMode: "Incremental"
            displayName: "Deploy resources to Azure"
