# CI/PR Pipeline that deploys an ARM template to create or update the resources needed by the other pipelines.
trigger:
  branches:
    include:
      - adf_publish

pr:
  branches:
    include:
      - adf_publish


pool:
  vmImage: "ubuntu-latest"

variables:
  - group: devops-iac-vg
  - name: factoryName
  - name: AzureKeyVault_properties_typeProperties_baseUrl
  - name: soucefactory

steps:
  - checkout: git://${{variables['System.TeamProject']}}@adf_publish
  - script: dir $(Build.SourcesDirectory)

  - task: Bash@3
    displayName: Set variable
    inputs:
      targetType: 'inline'
      script: |
        # Write your commands here
        echo '##vso[task.setvariable variable=factoryName]$(LANDSCAPE_NAME)-adf-$(BASE_NAME)'  
        echo '##vso[task.setvariable variable=soucefactory]dev-adf-$(BASE_NAME)'  
        echo '##vso[task.setvariable variable=AzureKeyVault_properties_typeProperties_baseUrl]https://$(LANDSCAPE_NAME)-akv-$(BASE_NAME).vault.azure.net/'
  - task: Bash@3
    displayName: show variable
    inputs:
      targetType: 'inline'
      script: |
        # Write your commands here
        echo factory name is $(factoryName)
        echo akv uri is  $(AzureKeyVault_properties_typeProperties_baseUrl)

  - task: AzureResourceGroupDeployment@2
    inputs:
      azureSubscription: "$(AZURE_RM_SVC_CONNECTION)"
      action: "Create Or Update Resource Group"
      resourceGroupName: "$(RESOURCE_GROUP)"
      location: $(LOCATION)
      templateLocation: "Linked artifact"
      csmFile: '$(Build.SourcesDirectory)/$(soucefactory)/ARMTemplateForFactory.json'
      csmParametersFile: '$(Build.SourcesDirectory)/$(soucefactory)/ARMTemplateParametersForFactory.json'
      overrideParameters: -factoryName $(factoryName) -AzureKeyVault_properties_typeProperties_baseUrl "$(AzureKeyVault_properties_typeProperties_baseUrl)"
      deploymentMode: "Incremental"
    displayName: "Deploy resources to Azure"
