# CI/PR Pipeline that deploys an ARM template to create or update the resources needed by the other pipelines.
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - 00_Environment/*
pr:
  branches:
    include:
      - master
  paths:
    include:
      - 00_Environment/*

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: devops-iac-vg

steps:
  - task: AzureResourceGroupDeployment@2
    inputs:
      azureSubscription: "$(AZURE_RM_SVC_CONNECTION)"
      action: "Create Or Update Resource Group"
      resourceGroupName: "$(RESOURCE_GROUP)"
      location: $(LOCATION)
      templateLocation: "Linked artifact"
      csmFile: "$(Build.SourcesDirectory)/00_Environment/**/azureDeploy.json"
      overrideParameters: "-landscape_name $(LANDSCAPE_NAME) -base_name $(BASE_NAME) -sql_login $(SQL_LOGIN) -sql_pass $(SQL_PASS) -grant_ip $(GRANT_IP)"
      deploymentMode: "Incremental"
    displayName: "Deploy resources to Azure"
